[project]
name = "services-pets"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
requires-python = ">=3.13"

[[tool.poetry.source]]
name = "azure"
url = "https://pkgs.dev.azure.com/adrianhawkinsportfolio/adrian-hawkins-portfolio/_packaging/adoption-agency/pypi/simple/"
priority = "primary"

[tool.poetry.dependencies]
adoption-agency-common = {version = "^5", source = "azure"}
[tool.poetry]
packages = [{ include = "pet_service", from = "src" }]

[tool.poetry.scripts]
pet-service = "pet_service.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
